server:
  port: 8001

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml #定义mybatis配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml      #定义扫描mapper位置的属性
  type-aliases-package: ahead.pojo  # 指定POJO扫描包来让mybatis自动扫描到自定义POJO （springcloud-api模块中的Javabean位置）


# spring配置
spring:
  application:
    name: springcloud-provider-dept  #微服务项目起到唯一标识的作用，（让注册中心知道你注册的这个服务实例，逻辑上是属于哪个服务的）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456











